services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bff-sp-users:local
    container_name: bff-sp-users
    env_file:
      - .env.docker
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    restart: unless-stopped
